### ISSUE TITLE
Looking for the text case explaination or documentation.

### ISSUE THREAD

**Issue by bharatsewani1993** [rylans/getlang#6]
I added Punjabi language support to this package and run on my local machine. When I submitted the pull request there was a build failed indicated by Tarvis. I want to contribute to this Repo and want to fix the error of my code. If I could get any documentation or guidance it will help me a lot. 
Thank you
Bharat Sewani

**Comment by rylans** [comment]
Thanks for the contribution Bharat. 
I noticed one test failure is because the word 'Punjabi' was misspelt as 'Panjabi'
The other test failure about Russian categorization may be because adding a language reduces the confidence of other languages. You may need play with the TestRussianPhraseUDHR test to add more Russian language.

**Comment by bharatsewani1993** [comment]
Thank you for writing the details comments under the files, It helped me to fix the issue. I added support to Punjabi and in future, I'll try to add more languages to it.
Thank you
Bharat Sewani
